name = "svelte"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2024-05-01"
compatibility_flags = [ "nodejs_compat" ]
keep_vars = true

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"
